import pino from "pino";

import { env } from "../../config/env.js";

export const logger = pino({
    level: env.LOG_LEVEL,
    base: {
        service: "proxiai-api",
        environment: env.NODE_ENV,
    },
    redact: {
        paths: [
            "req.headers.authorization",
            "req.headers.cookie",
            "headers.authorization",
            "headers.cookie",
            "password",
            "*.password",
            "token",
            "*.token",
            "accessToken",
            "*.accessToken",
            "refreshToken",
            "*.refreshToken",
            "resetToken",
            "*.resetToken",
            "apiKey",
            "*.apiKey",
            "secret",
            "*.secret",
            "prompt",
            "*.prompt",
            "response",
            "*.response",
            "responseText",
            "*.responseText",
            "promptEnc",
            "*.promptEnc",
            "responseEnc",
            "*.responseEnc",
            "contentEnc",
            "*.contentEnc",
            "encryptionKey",
            "*.encryptionKey",
            "MONGO_URI",
            "*.MONGO_URI",
            "REDIS_URL",
            "*.REDIS_URL",
            "mongoUri",
            "*.mongoUri",
            "redisUrl",
            "*.redisUrl",
            "connectionString",
            "*.connectionString",
        ],
        censor: "[REDACTED]",
    },
});
